apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: us-south1-docker.pkg.dev/micro-chiller-458819-r4/oreo-repository/users:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: users-config
          env:
            - name : MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: MONGO_URI 